all:
	gcc -o prog1 prog1.c
	gcc -o prog2 prog2.c
	gcc -o prog3 prog3.c
	gcc -o prog4 prog4.c
	gcc -o prog5 prog5.c
	gcc -o prog6 prog6.c
	gcc -o prog7 prog7.c
	gcc -o prog8 prog8.c
	gcc -o prog9 prog9.c
	gcc -o prog10 prog10.c
	gcc -o prog11 prog11.c
	gcc -o prog12 prog12.c
	gcc -o prog13 prog13.c
	gcc -o prog14 prog14.c
	gcc -o prog15 prog15.c
	gcc -o prog16 prog16.c
	gcc -o prog17 prog17.c
	gcc -o prog18 prog18.c
	gcc -o prog19 prog19.c
	gcc -o prog20 prog20.c
	gcc -o prog21 prog21.c
	gcc -o prog22 prog22.c
clean:
	rm prog1 prog2 prog3 prog4 prog5 prog6 prog7 prog8 prog9 prog10 prog11 prog12 prog13 prog14 prog15 prog16 prog17 prog18 prog19 prog20 prog21 prog22
