all:
	gcc -o prog-1 prog-1.c
	gcc -o prog-2 prog-2.c
	gcc -o prog-3 prog-3.c -lm
	gcc -o prog-4 prog-4.c
	gcc -o prog-5 prog-5.c
	gcc -o prog-6 prog-6.c
clean:
	rm prog-1 prog-2 prog-3 prog-4 prog-5 prog-6
