all:
	gcc -o prog-1 prog-1.c
	gcc -o prog-2 prog-2.c
	gcc -o prog-3 prog-3.c
	gcc -o prog-4 prog-4.c
	gcc -o prog-5 prog-5.c
	gcc -o prog-6 prog-6.c
	gcc -o prog-7 prog-7.c
	gcc -o prog-8 prog-8.c
	gcc -o prog-9 prog-9.c
	gcc -o prog-10 prog-10.c
	gcc -o prog-11 prog-11.c
	gcc -o prog-12 prog-12.c
	gcc -o prog-13 prog-13.c
	gcc -o prog-14 prog-14.c
	gcc -o prog-15 prog-15.c
clean:
	rm prog-1 prog-2 prog-3 prog-4 prog-5 prog-6 prog-7 prog-8 prog-9 prog-10 prog-11 prog-12 prog-13 prog-14 prog-15
